### ISSUE TITLE
Generate and display Code Coverage report

### ISSUE THREAD

**Issue by eddievelasquez** [eddievelasquez/Bach#15]
See [Generating Code Coverage Reports in .NET Core](https://dotnetthoughts.net/generating-code-coverage-reports-in-dotnet-core/) for ideas.

Steps for generating locally:

- `dotnet tool install --global dotnet-coverage`
- `dotnet tool install --global dotnet-reportgenerator-globaltool`
- `dotnet coverage collect dotnet test Bach.sln --configuration Release --no-build --verbosity normal --output ./tests/coverage/coverage.xml --output-format cobertura`
- `reportgenerator -reports:./tests/coverage/coverage.xml -targetdir:./tests/coverage/report -reporttypes:Html -assemblyfilters:+Bach.Model`

A partial GitHub action for this could be: 
```yaml
- name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-reportgenerator-globaltool
          dotnet tool install dotnet-coverage

      - name: Run the unit tests with code coverage
        run: dotnet coverage collect dotnet test Bach.sln --configuration Release --no-build --verbosity normal --output ${{ github.workspace }}/tests/coverage/coverage.xml --output-format cobertura
        
      - name: Generate Report
        run:
          dotnet reportgenerator -reports:${{ github.workspace }}/tests/coverage/coverage.xml -targetdir:"${{ gitgub.workspace }}/tests/coverage/report" -reporttypes:Html -assemblyfilters:+Bach.Model          
```
Still need to figure out how to export the HTML report as an artifact and publish to GitHub Pages.
